buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://verve.jfrog.io/artifactory/verve-gradle-release' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://verve.jfrog.io/artifactory/verve-gradle-release' }
    }
}
